# This is a basic workflow to help you get started with Actions

name: build_kernel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: setup configuration
        run: |
          echo Setup Configuration
          
          
      - name: download kernel source
        run: |
          cd $GITHUB_WORKSPACE && mkdir kernel_workspace && cd kernel_workspace
          git clone 'https://github.com/nozomanai/crDroid-android_kernel_xiaomi_cepheus.git' -b 13.0 android-kernel --depth=1
          
      - name: setup build kernel environment
        run: |
          sudo apt-get update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk language-pack-zh-hans
          sudo apt-get install libyaml-cpp-dev
          apt list
          
      - name: build kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          rm .git -R
          sudo bash build.sh

