name: EvolutionX_build_kernel

env:
  KERNEL_SOURCE: 'https://github.com/chematelegram/kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH: 'tiramisu'
  KERNEL_DEFCONFIG: 'cepheus_defconfig'
  KERNEL_NAME: 'EvolutionX'
  
on:
#   schedule:
#     - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: run build script
        run: |
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M%S")" >> $GITHUB_ENV
          bash scripts/Evasi0nKernelBuild.sh ${{env.KERNEL_SOURCE}} ${{env.KERNEL_SOURCE_BRANCH}} ${{env.KERNEL_DEFCONFIG}} ${{env.KERNEL_NAME}} 
          
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ env.BUILD_TIME }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kernel_workspace/android-kernel/out/*.zip
