name: PixelOS_build_kernel
env:
  KERNEL_SOURCE: 'https://github.com/balgxmr/kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH: 'thirteen'
  KERNEL_DEFCONFIG: 'cepheus_defconfig'
  KERNEL_NAME: 'PixelOS'
  
on:

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: download kernel source
        run: |
          cd $GITHUB_WORKSPACE && mkdir kernel_workspace && cd kernel_workspace
          git clone ${{ github.event.inputs.KERNEL_SOURCE }} -b ${{ github.event.inputs.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1

      - name: setup build kernel environment
        run: |
          pwd
          cp $GITHUB_WORKSPACE/patch/anykernel.sh $GITHUB_WORKSPACE/patch/build.sh $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          ls -l
          
          sed -i 's/DATE=.*/DATE=$(date "+%Y%m%d%H%M%S")/g' build.sh
          sed -i "s/KERNEL_NAME=.*/KERNEL_NAME=${KERNEL_NAME}-$DATE/g" build.sh

      - name: add kernelsu 
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel

          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/${{ github.event.inputs.KERNEL_DEFCONFIG }}
          echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/${{ github.event.inputs.KERNEL_DEFCONFIG }}
          echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/${{ github.event.inputs.KERNEL_DEFCONFIG }}

          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
      

      - name: build kernel
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          rm .git -R
          sudo bash build.sh
          
          
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kernel_workspace/android-kernel/out/*.zip
